### ISSUE TITLE
where is the contract repo

### ISSUE THREAD

**Issue by huahuayu** [BarnBridge/barnbridge-yieldfarm-cli#1]
hi, I can see your contract is at https://etherscan.io/address/0xb0fa2beee3cf36a7ac7e99b885b48538ab364853#code but where is your contract github repo?

Usually, the contract deployed to mainnet is a single file, but you deployed it with many separate files, before investment I want to deploy it to testnet for review, I have some knowledge in solidity, can you please show me the method briefly? thanks!

**Comment by lacasian** [comment]
Hey @huahuayu! You can find the yield farming contracts here: https://github.com/BarnBridge/BarnBridge-YieldFarming
Please use our [discord channel](https://discord.com/invite/FfEhsVk) for questions.
